### ISSUE TITLE
Is starting outside the space confusing?

### ISSUE THREAD

**Issue by karth295** [invisible-college/tawk.space#14]
It seems like when you open tawkspace, your attention is drawn to the people already there, rather than your own tiny box in a corner. It takes a while to figure out that you have to move yourself.

We could instead get rid of the topbar entirely (except for the textbox with your name?), and mandate that users have to be in a group. You start out in your own group, and you can join other groups. 

Thoughts?

**Comment by toomim** [comment]
Good thinking!

I *do* see a use-case when we embed a tawk.space on a different site for users to load the page and be an audience, without having their video chat turn on. But in this case, I think a "Join" button would be better than "drag yourself into a group". And this might be an optional feature—off by default on https://tawk.space itself.

Also, you might prefer to default-join group 1, rather than sit in your own group. In your own group, you won't be able to hear or talk to other people very well, and it might be hard for them to tell you "hey, you need to drag yourself into our group".

**Comment by toomim** [comment]
We might also want icons at the top to see everyone observing the discussion, who doesn't have their cameras on, so that participants know someone is watching.
